// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKK3d7U-93u6cIKlmsPEpE1qNjapcrk8',
    appId: '1:13562873912:web:9af28a4f9735eb9933becd',
    messagingSenderId: '13562873912',
    projectId: 'dersini-bil',
    authDomain: 'dersini-bil.firebaseapp.com',
    storageBucket: 'dersini-bil.firebasestorage.app',
    measurementId: 'G-BCNWRGQER6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRVE7V6-goUCU03TFKrHrrBcgld84HbA4',
    appId: '1:13562873912:android:d78efae6868a534e33becd',
    messagingSenderId: '13562873912',
    projectId: 'dersini-bil',
    storageBucket: 'dersini-bil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzqWuRN1ceBUbnD2AsCVqD5BnBV5wQFbU',
    appId: '1:13562873912:ios:a860b0c2d3839dfe33becd',
    messagingSenderId: '13562873912',
    projectId: 'dersini-bil',
    storageBucket: 'dersini-bil.firebasestorage.app',
    iosBundleId: 'com.dersinibil.dersiniBil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzqWuRN1ceBUbnD2AsCVqD5BnBV5wQFbU',
    appId: '1:13562873912:ios:a860b0c2d3839dfe33becd',
    messagingSenderId: '13562873912',
    projectId: 'dersini-bil',
    storageBucket: 'dersini-bil.firebasestorage.app',
    iosBundleId: 'com.dersinibil.dersiniBil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYKK3d7U-93u6cIKlmsPEpE1qNjapcrk8',
    appId: '1:13562873912:web:75059c502ab5d03133becd',
    messagingSenderId: '13562873912',
    projectId: 'dersini-bil',
    authDomain: 'dersini-bil.firebaseapp.com',
    storageBucket: 'dersini-bil.firebasestorage.app',
    measurementId: 'G-ZFN2Z45VWT',
  );
}
